//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egg
    {
        public System.DateTime Date { get; set; }
        public int CollectedEggs { get; set; }
        public Nullable<int> GoodEggs { get; set; }
        public Nullable<int> BadEggs { get; set; }
    }
}
