//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoultryManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feeding
    {
        public System.DateTime Date { get; set; }
        public string FeedName { get; set; }
        public int Quantity { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Comment { get; set; }
    }
}
